"""locale_default_seting

Revision ID: 4d1613611f63
Revises: 7c02706e4dfb
Create Date: 2025-05-27 14:49:25.386308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1613611f63'
down_revision = '7c02706e4dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
