"""device_group

Revision ID: 7c02706e4dfb
Revises: cb0a5f39ca58
Create Date: 2025-05-27 11:04:44.987242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c02706e4dfb'
down_revision = 'cb0a5f39ca58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('group')

    # ### end Alembic commands ###
