"""init

Revision ID: c173c5b98921
Revises: 
Create Date: 2025-05-19 15:12:20.990465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c173c5b98921'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('passphrase', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('u_type', sa.Enum('ADMIN', 'USER', name='user_type'), nullable=False),
    sa.Column('u_state', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', name='user_state'), nullable=False),
    sa.Column('dt_created', sa.Integer(), nullable=True),
    sa.Column('dt_updated', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=128), nullable=False),
    sa.Column('a_state', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', name='device_state'), nullable=False),
    sa.Column('dt_created', sa.Integer(), nullable=True),
    sa.Column('dt_updated', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files_trk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('file', sa.LargeBinary(), nullable=False),
    sa.Column('file_state', sa.Enum('UPLOADED', 'PROCESSED', 'DELETED', name='file_state'), nullable=False),
    sa.Column('dt_created', sa.Integer(), nullable=True),
    sa.Column('dt_updated', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files_trk')
    op.drop_table('devices')
    op.drop_table('users')
    # ### end Alembic commands ###
