"""screen group

Revision ID: cb0a5f39ca58
Revises: fca89f1b9733
Create Date: 2025-05-26 10:52:47.910977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0a5f39ca58'
down_revision = 'fca89f1b9733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files_trk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('group', sa.String(length=12), nullable=False))
        batch_op.drop_column('file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files_trk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.BLOB(), nullable=False))
        batch_op.drop_column('group')
        batch_op.drop_column('filepath')

    # ### end Alembic commands ###
